apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "als-oracle-pathfinder.fullname" . }}
  labels:
    app: {{ template "als-oracle-pathfinder.name" . }}
    chart: {{ template "als-oracle-pathfinder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "als-oracle-pathfinder.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "als-oracle-pathfinder.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
        - name: {{ template "als-oracle-pathfinder.fullname" . }}-tls
          mountPath: {{ .Values.pathfinder.secretsMountPoint }}
        envFrom:
        - configMapRef:
            name: {{ template "als-oracle-pathfinder.fullname" . }}
        - secretRef:
            name:  {{ template "als-oracle-pathfinder.fullname" . }}-db
      volumes:
      - name: {{ template "als-oracle-pathfinder.fullname" . }}-tls
        secret:
          secretName: {{ template "als-oracle-pathfinder.fullname" . }}-tls
          defaultMode: 511
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets.name }}
