apiVersion: v1
kind: Secret
metadata:
  name: {{ template "als-oracle-pathfinder.fullname" . }}-tls
  labels:
      app: {{ template "als-oracle-pathfinder.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
type: Opaque
data:
  clientcert.pem: |-
    {{ required "Our client certificate is required to authenticate with Pathfinder" (.Files.Get .Values.pathfinder.tls.client_cert_path) | b64enc }}
  clientkey.pem: |-
    {{ required "Our client key is required to encrypt communication with Pathfinder" (.Files.Get .Values.pathfinder.tls.client_key_path) | b64enc }}
  pathfindercert.pem: |-
    {{ required "The Pathfinder server certificate is required to authenticate Pathfinder" (.Files.Get .Values.pathfinder.tls.root_cert_path) | b64enc }}
  pathfinderintermediatecert.pem: |-
    {{ default "" (.Files.Get .Values.pathfinder.tls.intermediate_cert_path | b64enc) }}
