# Default values for casa-close-settlement-window.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: casablanca-casa-docker-release.jfrog.io/als-oracle-pathfinder
  tag: 10.4.1
  pullPolicy: Always
  imagePullSecrets:
    name: dock-casa-secret

service:
  type: ClusterIP
  port: 80

db: 
  protocol: 'mysql'
  host: '$release_name-centralledger-mysql'
  port: '3306'
  user: 'central_ledger'
  password: 'oyMxgZChuu'
  schema: 'central_ledger'

accountLookupDbSchema: 'account_lookup'

pathfinder:
  host: '156.154.59.224'
  port: 7007
  queryTimeoutMs: 10000
  secretsMountPoint: '/secrets' # absolute path in the container
  tls:
    # rejectUnauthorized should be true in production
    rejectUnauthorized: false
    # The following paths are all relative to this directory containing the values file
    client_cert_path: 'secrets/clientcert.pem'
    client_key_path: 'secrets/clientkey.pem'
    root_cert_path: 'secrets/pathfindercert.pem'
    # Intermediate cert is optional, but will likely be required for mutual auth if
    # rejectUnauthorized is true, as Neustar's certificate doesn't seem to have been signed by any
    # certs in the Mozilla bundle, which is used by Node as default.
    intermediate_cert_path: 'secrets/pathfinder_intermediate_cert.pem'
